HW1: (Total 60 points)
Coding 50 points
report 10 points

Submission:
Submit your code as ipynb and report as pdf file through canvas.

Loading data:

In [49]:
import numpy as np
import pandas as pd
import math
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LinearRegression
from google.colab import drive

print("Imported the modules.")

test_path = "california_housing_test.csv"
train_path = "california_housing_train.csv"
# Load the dataset
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

#print(train_df)
# Shuffle the examples
np.random.seed(0) # fix the random seed
train_df = train_df.reindex(np.random.permutation(train_df.index))
# Processing training set
X = train_df[['longitude', 'latitude','street_name']]
Y = train_df['median_house_value']
# Processing testing set
X_test = test_df[['longitude', 'latitude','street_name']]
Y_test = test_df['median_house_value']
np_x = X.to_numpy()
np_y = Y.to_numpy()
np_test_x = X_test.to_numpy()
np_test_y = Y_test.to_numpy()
#print("X")
#print(np_x.shape)
#print("Y")
#print(np_y.shape)
#print("X TEST")
#print(np_test_x.shape)
#print("Y TEST")
#print(np_test_y.shape)
#print(np_test_x)


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Imported the modules.


**Question 1** [10-points]: Do k fold split to your data. Split the data into 10 parts

Note that Don't use any sort of library like Sk-learn

Evaluation metric: After the split you suppose to reunion them and get back the same original set. If not, there is a bug

In [50]:
def eval_kfold (train_index, val_index):
    #print("EVAL K FOLD")
    all_indx = np.concatenate((train_index, val_index))
    all_indx.sort()
    original = np.arange(all_indx.shape[0])
    #print("ORIGINAL: ",original)
    #print("ALL INDX: ", all_indx)
    for i in range(original.shape[0]):
        if all_indx[i] != original[i]: print("ERROR: Your K-fold split has a bug")
    #print("ended")
    return all_indx

This is how it suppose to be like using sk-learn 


In [ ]:
#print("X: ", X)
#print("NP X: ", np_x.shape)
kf = KFold(n_splits=10,shuffle=True)
kf.get_n_splits(np_x)
#Takes 1/10 of the thing, and assigns those indeces to val indeces, and the other 9/10 are train indeces
for train_index, val_index in kf.split(np_x):
    #print("TRAIN INDEX: ", train_index),
    #print("VAL INDEX: ", val_index)
    eval_kfold (train_index, val_index)
    X_train, X_val = np_x[train_index], np_x[val_index]
    y_train, y_val = np_y[train_index], np_y[val_index]

In [51]:
#### Your code starts here###

#BASIC VERSION, THIS ONE DOESN'T RANDOMIZE THE INDECES
np_x = X.to_numpy()
np_y = Y.to_numpy()
change_amount = np_x.shape[0]/10
index_list = np.arange(np_x.shape[0])
first_10 = np_x[:10]
for x in range(10):
    test_list = index_list[int(x*change_amount): int((x+1)*change_amount)]
    train_list_ind = np.append(index_list[0:(int(x*change_amount))], index_list[int((x+1)*change_amount):])
    eval_kfold(train_list_ind, test_list)
    test_x = np_x[int(x*change_amount): int((x+1)*change_amount)]
    test_y = np_y[int(x*change_amount): int((x+1)*change_amount)]
    train_x = np.append(np_x[0:(int(x*change_amount))], np_x[int((x+1)*change_amount):])
    train_x.shape = (180, 3)
    train_y = np.append(np_y[0:(int(x*change_amount))], np_y[int((x+1)*change_amount):])
    train_y.shape = (180, 1)
    print("TEST LIST")
    print(test_list)
    print("TRAIN LIST")
    print(train_list_ind)


TEST LIST
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
TRAIN LIST
[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199]
TEST LIST
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
TRAIN LIST
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  40  41  42  43  44  

**Question 2** [10-points]: Encode street_name feature into one hot incoding and print out the result.

Note that Don't use any sort of library like Sk-learn

Evluation metric: print out your encoding 

In [63]:
#### Your code starts here###

new_col_2 = np.zeros((np_x.shape[0], 9))
total = np.hstack((np_x, new_col_2))
for i in range(total.shape[0]):
    name = total[i][2]
    if(name == "oakes"):
        total[i][3+0] = 1
    elif(name == "stevenson"):
        total[i][3+1] = 1
    elif(name == "crown"):
        total[i][3+2] = 1
    elif(name == "merrill"):
        total[i][3+3] = 1
    elif(name == "nine"):
        total[i][3+4] = 1
    elif(name == "ten"):
        total[i][3+5] = 1
    elif(name == "rc"):
        total[i][3+6] = 1
    elif(name == "kresge"):
        total[i][3+7] = 1
    elif(name == "porter"):
        total[i][3+8] = 1
print("TOTAL 10 ELEMENTS: ")
print(total[0:10])

TOTAL 10 ELEMENTS: 
[[-114.66 32.74 'oakes' 1 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [-116.25 33.75 'kresge' 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1 0.0]
 [-115.69 32.79 'nine' 0.0 0.0 0.0 0.0 1 0.0 0.0 0.0 0.0]
 [-115.58 32.78 'merrill' 0.0 0.0 0.0 1 0.0 0.0 0.0 0.0 0.0]
 [-116.3 33.68 'kresge' 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1 0.0]
 [-116.32 34.14 'porter' 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1]
 [-114.58 33.63 'oakes' 1 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [-116.18 33.69 'rc' 0.0 0.0 0.0 0.0 0.0 0.0 1 0.0 0.0]
 [-114.61 34.84 'oakes' 1 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0]
 [-116.21 33.75 'rc' 0.0 0.0 0.0 0.0 0.0 0.0 1 0.0 0.0]]


**Question 3** [10-points]: Feture crossing

Given the bin version of the feature longitude and latitude. Please build the feature cross version of these two feature and print it out

Note that Don't use any sort of library like Sk-learn

Evluation metric: print out your encoding. Explain what you did and what does it means


In [57]:
def create_one_hot_features(df, feature_name, bin_number):
 # print(bin_number)
  df[feature_name+'_bin'] = pd.cut(df[feature_name], bins=bin_number)
  df_encoded = pd.get_dummies(df, columns=[feature_name+'_bin'])
  return df_encoded

# Here is the given bins
bins_longitude = pd.IntervalIndex.from_tuples([(-125, -121), (-121, -117), (-117, -113)])
bins_latitude = pd.IntervalIndex.from_tuples([(32,33),(33,34), (34,35),(35,36)])
#-114.66     32.74

# One hot encoding using sk-learn
X_longitude_encoded = create_one_hot_features(X, 'longitude', bins_longitude)
X_test_longitude_encoded = create_one_hot_features(X_test, 'longitude', bins_longitude)
#print(X_longitude_encoded)
np_lat_x = X_longitude_encoded.to_numpy()
#print(np_lat_x[0][3])
X_latitude_encoded = create_one_hot_features(X, 'latitude', bins_latitude)
X_test_latitude_encoded = create_one_hot_features(X_test, 'latitude', bins_latitude)

In [64]:
# Your code starts here
#Make 12 new rows
#long x, lat y, index of new column is x*(num of longs(3))+y
def create_crossed_feature(df, df_start_ind, long, num_long, lat, num_lat, start_ind):
  num_of_each = [0,0,0,0,0,0,0,0,0,0,0,0,0]
  for x in range(df.shape[0]):
    cur_pos = df_start_ind
    for y in range(num_long):
      if long[x][y+start_ind] == 1:
          cur_pos += y*num_lat
    for y in range(num_lat):
      if lat[x][y+start_ind] == 1:
          cur_pos += y
    num_of_each[cur_pos] += 1
    df[x][cur_pos] = 1

new_np_x = np.copy(np_x)
crossed_features = np.zeros((new_np_x.shape[0], 13))
np_lat_x = X_latitude_encoded.to_numpy()
np_long_x = X_longitude_encoded.to_numpy()
for x in range(crossed_features.shape[0]):
    crossed_features[x][0] = 1 
create_crossed_feature(crossed_features, 1, np_long_x, 3, np_lat_x, 4, 4)
print(np_x[0])
print("CROSSED FEATURES FIRST 10")
print(crossed_features[0:10])


[-114.66 32.74 'oakes']
CROSSED FEATURES FIRST 10
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


**Question 4** [10-points]: Linear Regression

From question 3 we now have 13 parameters 3*4+1. 3 from longitude, 4 from latitude and 1 bias. 

Do a linear fit to predict the house price by using these 13 parameters 

Evluation metric: print out the accuracy when you test the linear model on test dataset


In [62]:
# Refer to in class exercise as your starter code
# The in class we only deal with low dimention input case. Now try to make it 
# works in this case.
# Hint: Take a look at these two functions. Feel free to reuse some of the 
# exercise code we provided. 
"""
    Performs gradient descent to learn `theta`. Updates theta by taking `num_iters`
    gradient steps with learning rate `alpha`.
    
    Parameters
    ----------
    X : array_like
        The input dataset of shape (m x n+1).
    
    y : array_like
        Value at given features. A vector of shape (m, ).
    
    theta : array_like
        Initial values for the linear regression parameters. 
        A vector of shape (n+1, ).
    
    alpha : float
        The learning rate.
    
    num_iters : int
        The number of iterations for gradient descent.
"""
def find_actual_vals(y_data, crossed_data):
    num_of_each = [0,0,0,0,0,0,0,0,0,0,0,0,0]
    med_price = [0,0,0,0,0,0,0,0,0,0,0,0,0]
    for x in range(y_data.shape[0]):
            if math.isnan(y_data[x]):
               continue
            value_vec = y_data[x]*crossed_data[x]
            for y in range(value_vec.shape[0]):
                if y != 0:  
                    num_of_each[y-1] += crossed_data[x][y]
                    med_price[y-1] += value_vec[y]
    for x in range(12):
        med_price[x] = med_price[x] / num_of_each[x]
    print("MED PRICE")
    print(med_price)
    print("NUM EACH")
    print(num_of_each)
iterations = 1500
alpha = 0.01
theta = np.zeros(crossed_features.shape[1])
med_vals = np.zeros(crossed_features.shape[0])
find_actual_vals(np_y, crossed_features)
def computeCost(X, y, theta, j):
    J = np.sum(((X @ theta) - y) * X[:,j])
    return J

def gradientDescent(X, y, theta, alpha, num_iters):
    m = y.shape[0]
    
    for i in range(num_iters):
        theta_tmp = []    
        for j in range(len(theta)): # partial derivative 
            gradient = (alpha/m) * computeCost(X, y, theta, j)
            new_theta = theta[j] - gradient
            theta_tmp.append(new_theta)        
        theta = theta_tmp
    print("THETA FINAL:")
    print(theta)
    return theta

end_theta = gradientDescent(crossed_features, np_y, theta, alpha, iterations)

crossed_features_test = np.zeros((np_test_x.shape[0], 13))
np_lat_x = X_latitude_encoded.to_numpy()
np_long_x = X_longitude_encoded.to_numpy()
for x in range(crossed_features_test.shape[0]):
    crossed_features_test[x][0] = 1 
np_lat_test_x = X_test_latitude_encoded.to_numpy()
np_long_test_x = X_test_longitude_encoded.to_numpy()
create_crossed_feature(crossed_features_test, 1, np_long_test_x, 3, np_lat_test_x, 4, 4)
find_actual_vals(np_test_y, crossed_features_test)
#*(275000.0-(20910+58181))+ (194400-58181)*14+(125016-58181)*6+(201864-58181)*14+(275833-58181)*12+(112600-58181)*2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:51: RuntimeWarning: invalid value encountered in double_scalars


MED PRICE
[nan, nan, nan, nan, nan, nan, nan, nan, 79155.55555555556, 91647.77777777778, 62774.07407407407, 50200.0, 0]
NUM EACH
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 81.0, 90.0, 27.0, 2.0, 0]
THETA FINAL:
[58181.376745520436, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 20910.18572742563, 33397.12240677291, 4660.114788089822, -786.0461767679182]
MED PRICE
[194400.0, nan, nan, nan, 125016.66666666667, 201864.2857142857, 275833.4166666667, 112600.0, 275000.0, nan, nan, nan, 0]
NUM EACH
[14.0, 0.0, 0.0, 0.0, 6.0, 14.0, 12.0, 2.0, 1.0, 0.0, 0.0, 0.0, 0]
